[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "nf-peekaboo"
authors = [{name = "Olivia Ellis", email = "olivia.ellis1@lilly.com"}]
dynamic = ["version", "description"]
